services:
  db:
    image: postgres:15-alpine
    container_name: cloud_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: cloud_db
      POSTGRES_USER: cloud_user
      POSTGRES_PASSWORD: cloud_pass_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cloud_user -d cloud_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: cloud_redis_dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloud_web_dev
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      DEBUG: "True"
      SECRET_KEY: django-insecure-dev-key
      ALLOWED_HOSTS: "localhost,127.0.0.1"
      CSRF_TRUSTED_ORIGINS: "http://localhost:8000,http://127.0.0.1:8000"
      DB_NAME: cloud_db
      DB_USER: cloud_user
      DB_PASSWORD: cloud_pass_123
      DB_HOST: db
      DB_PORT: "5432"
      REDIS_URL: redis://redis:6379/1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data_dev:
  redis_data_dev:
